import type { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: '1',
    name: 'Greek Yogurt Parfait',
    description: 'A protein-packed breakfast with fresh berries and granola',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 280,
    protein: 20,
    carbs: 35,
    fats: 6,
    ingredients: [
      '1 cup plain Greek yogurt',
      '1/2 cup mixed berries',
      '2 tbsp granola',
      '1 tsp honey',
      '1 tbsp sliced almonds',
    ],
    instructions: [
      'Layer Greek yogurt in a bowl or glass',
      'Add mixed berries on top',
      'Sprinkle with granola and almonds',
      'Drizzle with honey',
      'Serve immediately',
    ],
    tags: ['breakfast', 'quick', 'high-protein', 'vegetarian'],
  },
  {
    id: '2',
    name: 'Grilled Chicken Salad',
    description: 'Fresh greens with grilled chicken and balsamic vinaigrette',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 320,
    protein: 35,
    carbs: 18,
    fats: 12,
    ingredients: [
      '2 chicken breasts (6 oz each)',
      '4 cups mixed greens',
      '1 cup cherry tomatoes, halved',
      '1/2 cucumber, sliced',
      '1/4 red onion, thinly sliced',
      '2 tbsp balsamic vinaigrette',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Season chicken breasts with salt and pepper',
      'Grill chicken for 6-7 minutes per side until cooked through',
      'Let chicken rest for 5 minutes, then slice',
      'Combine greens, tomatoes, cucumber, and onion in a large bowl',
      'Top with sliced chicken',
      'Drizzle with balsamic vinaigrette',
      'Toss and serve',
    ],
    tags: ['lunch', 'dinner', 'high-protein', 'low-carb', 'gluten-free'],
  },
  {
    id: '3',
    name: 'Quinoa Buddha Bowl',
    description: 'Nutrient-dense bowl with quinoa, roasted vegetables, and tahini',
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    calories: 380,
    protein: 14,
    carbs: 52,
    fats: 14,
    ingredients: [
      '1 cup quinoa',
      '2 cups water',
      '1 sweet potato, cubed',
      '1 cup broccoli florets',
      '1 cup chickpeas, drained',
      '2 cups spinach',
      '2 tbsp tahini',
      '1 tbsp lemon juice',
      'Olive oil, salt, pepper',
    ],
    instructions: [
      'Cook quinoa according to package directions',
      'Preheat oven to 400°F (200°C)',
      'Toss sweet potato, broccoli, and chickpeas with olive oil, salt, and pepper',
      'Roast vegetables for 25-30 minutes until tender',
      'Mix tahini with lemon juice and a splash of water to make dressing',
      'Divide quinoa between bowls',
      'Top with roasted vegetables and fresh spinach',
      'Drizzle with tahini dressing',
    ],
    tags: ['lunch', 'dinner', 'vegetarian', 'vegan', 'high-fiber'],
  },
  {
    id: '4',
    name: 'Baked Salmon with Asparagus',
    description: 'Omega-3 rich salmon with roasted asparagus',
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    calories: 340,
    protein: 38,
    carbs: 8,
    fats: 18,
    ingredients: [
      '2 salmon fillets (6 oz each)',
      '1 bunch asparagus, trimmed',
      '2 cloves garlic, minced',
      '1 lemon, sliced',
      '2 tbsp olive oil',
      'Fresh dill',
      'Salt and pepper',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C)',
      'Place salmon and asparagus on a baking sheet',
      'Drizzle with olive oil and season with salt, pepper, and garlic',
      'Top salmon with lemon slices and dill',
      'Bake for 15-20 minutes until salmon flakes easily',
      'Serve immediately',
    ],
    tags: ['dinner', 'high-protein', 'low-carb', 'omega-3', 'gluten-free'],
  },
  {
    id: '5',
    name: 'Veggie Egg White Omelet',
    description: 'Light and fluffy omelet packed with vegetables',
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    calories: 180,
    protein: 22,
    carbs: 12,
    fats: 4,
    ingredients: [
      '4 egg whites',
      '1/2 cup spinach',
      '1/4 cup mushrooms, sliced',
      '1/4 cup bell peppers, diced',
      '2 tbsp onion, diced',
      'Cooking spray',
      'Salt and pepper',
    ],
    instructions: [
      'Spray a non-stick pan with cooking spray and heat over medium',
      'Sauté vegetables until tender, about 5 minutes',
      'Remove vegetables and set aside',
      'Whisk egg whites with salt and pepper',
      'Pour egg whites into the pan',
      'When edges start to set, add vegetables to one half',
      'Fold omelet in half and cook until fully set',
      'Slide onto plate and serve',
    ],
    tags: ['breakfast', 'high-protein', 'low-calorie', 'low-carb', 'vegetarian'],
  },
  {
    id: '6',
    name: 'Turkey Lettuce Wraps',
    description: 'Low-carb wraps with seasoned ground turkey',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 240,
    protein: 28,
    carbs: 10,
    fats: 10,
    ingredients: [
      '1 lb ground turkey',
      '1 tbsp olive oil',
      '2 cloves garlic, minced',
      '1 tbsp ginger, minced',
      '2 tbsp low-sodium soy sauce',
      '1 tsp sesame oil',
      '8 large lettuce leaves',
      '1/4 cup shredded carrots',
      'Green onions for garnish',
    ],
    instructions: [
      'Heat olive oil in a large skillet over medium-high heat',
      'Add garlic and ginger, cook for 30 seconds',
      'Add ground turkey and cook until browned, breaking it up as it cooks',
      'Stir in soy sauce and sesame oil',
      'Spoon turkey mixture into lettuce leaves',
      'Top with shredded carrots and green onions',
      'Serve immediately',
    ],
    tags: ['lunch', 'dinner', 'low-carb', 'high-protein', 'gluten-free'],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}

export function getRecipesByTag(tag: string): Recipe[] {
  return recipes.filter((r) => r.tags.includes(tag));
}

export function getAllTags(): string[] {
  const tags = new Set<string>();
  recipes.forEach((r) => r.tags.forEach((t) => tags.add(t)));
  return Array.from(tags).sort();
}

